{"cells":[{"cell_type":"markdown","metadata":{},"source":["## ðŸ’¥  Exception Handling\n","It is important to write non-crashing programs in any language. Of course, there is no flawless program (except in this lab, of course!), so we need to write specific code that handles exceptions that may occur.\n","\n","Execption handling is simple: surround the vulnerable code with a `try-except` block (analogue of try-catch in C++). \n","\n","**Good Practice** provide expressive messages when handling errors, it will reduce time and give readable clean code."]},{"cell_type":"code","execution_count":1,"metadata":{},"outputs":[],"source":["def safe_divide(numerator, denominator):\n","    quotient = None ## quotient of dividing the numerator by the denominator\n","    try:\n","        quotient = numerator / denominator\n","    except ZeroDivisionError: ## if the denominator was zero, this exception will be thrown\n","        print('Error: Denominator cannot be zero!')\n","        \n","    return quotient ## will return None if the exception is thrown, or the division result otherwise"]},{"cell_type":"code","execution_count":2,"metadata":{},"outputs":[{"data":{"text/plain":["5.0"]},"execution_count":2,"metadata":{},"output_type":"execute_result"}],"source":["safe_divide(10, 2) ## runs normally"]},{"cell_type":"code","execution_count":3,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":["Error: Denominator cannot be zero!\n"]}],"source":["safe_divide(10, 0) ## throws error"]},{"cell_type":"markdown","metadata":{},"source":["Can have multiple `except` blocks to handle different types of errors differently."]},{"cell_type":"code","execution_count":4,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":["Variable x is not defined. Error received: name 'x' is not defined\n"]}],"source":["try:\n","  print(x)\n","except NameError as e:\n","  # e has catches the error thrown by Python\n","  print(f\"Variable x is not defined. Error received: {e}\")\n","except:   # generic excepts are in general not a good practice (generic messages are bad)\n","  print(\"Something else went wrong\")"]},{"cell_type":"markdown","metadata":{},"source":["`finally` and `else`"]},{"cell_type":"code","execution_count":5,"metadata":{},"outputs":[{"name":"stdout","output_type":"stream","text":["A\n","else\n","finished\n"]},{"ename":"NameError","evalue":"name 'foo' is not defined","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)","Cell \u001b[0;32mIn[5], line 14\u001b[0m\n\u001b[1;32m     11\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mfinished\u001b[39m\u001b[38;5;124m\"\u001b[39m)       \u001b[38;5;66;03m# Executes anyway (even if there is an error)\u001b[39;00m\n\u001b[1;32m     13\u001b[0m \u001b[38;5;66;03m# executes only if there isn't an error\u001b[39;00m\n\u001b[0;32m---> 14\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[43mfoo\u001b[49m\u001b[38;5;241m.\u001b[39mread())\n","\u001b[0;31mNameError\u001b[0m: name 'foo' is not defined"]}],"source":["try:\n","    foo = open(\"foo.txt\")\n","except IOError:\n","    print(\"error\")\n","else:\n","    # executes only if there isn't an IOError. Can also have another try-except here (neater than below)\n","   bar = open(\"bar.text\")   \n","finally:\n","    print(\"finished\")       # Executes anyway (even if there is an error)\n","\n","# executes only if there isn't an error\n","print(foo.read())       "]},{"cell_type":"markdown","metadata":{},"source":["You can throw (i.e., `raise`) exceptions in your functions as well"]},{"cell_type":"code","execution_count":7,"metadata":{},"outputs":[],"source":["## this function accepts only numeric values\n","def add_5(value):\n","    if not isinstance(value, int) and not isinstance(value, float):  ## check if calue is numeric\n","        raise TypeError('value must be nuemric, found: ', type(value))\n","    ## if it is numeric\n","    return value + 5"]},{"cell_type":"code","execution_count":6,"metadata":{},"outputs":[{"ename":"NameError","evalue":"name 'add_5' is not defined","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)","Cell \u001b[0;32mIn[6], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43madd_5\u001b[49m(\u001b[38;5;241m5\u001b[39m)\n","\u001b[0;31mNameError\u001b[0m: name 'add_5' is not defined"]}],"source":["add_5(5)          ## works just fine"]},{"cell_type":"code","execution_count":9,"metadata":{},"outputs":[{"ename":"TypeError","evalue":"('value must be nuemric, found: ', <class 'str'>)","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","Cell \u001b[0;32mIn[9], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43madd_5\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43m5\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n","Cell \u001b[0;32mIn[7], line 4\u001b[0m, in \u001b[0;36madd_5\u001b[0;34m(value)\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21madd_5\u001b[39m(value):\n\u001b[1;32m      3\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(value, \u001b[38;5;28mint\u001b[39m) \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(value, \u001b[38;5;28mfloat\u001b[39m):  \u001b[38;5;66;03m## check if calue is numeric\u001b[39;00m\n\u001b[0;32m----> 4\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mvalue must be nuemric, found: \u001b[39m\u001b[38;5;124m'\u001b[39m, \u001b[38;5;28mtype\u001b[39m(value))\n\u001b[1;32m      6\u001b[0m     \u001b[38;5;66;03m## if it is numeric\u001b[39;00m\n\u001b[1;32m      7\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m value \u001b[38;5;241m+\u001b[39m \u001b[38;5;241m5\u001b[39m\n","\u001b[0;31mTypeError\u001b[0m: ('value must be nuemric, found: ', <class 'str'>)"]}],"source":["add_5(\"5\")      ## this will raise exception"]},{"cell_type":"markdown","metadata":{},"source":["When we want the program to throw an error under a known condition, we can use `assert`. This is typically used to test a function and throw an error if it behaves unexpectedly."]},{"cell_type":"code","execution_count":7,"metadata":{},"outputs":[{"ename":"AssertionError","evalue":"Adding 2 and 3 should give 5","output_type":"error","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mAssertionError\u001b[0m                            Traceback (most recent call last)","Cell \u001b[0;32mIn[7], line 5\u001b[0m\n\u001b[1;32m      2\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m x \u001b[38;5;241m-\u001b[39m y\n\u001b[1;32m      4\u001b[0m \u001b[38;5;66;03m# Test cases\u001b[39;00m\n\u001b[0;32m----> 5\u001b[0m \u001b[38;5;28;01massert\u001b[39;00m add(\u001b[38;5;241m2\u001b[39m, \u001b[38;5;241m3\u001b[39m) \u001b[38;5;241m==\u001b[39m \u001b[38;5;241m5\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mAdding 2 and 3 should give 5\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m      6\u001b[0m \u001b[38;5;28;01massert\u001b[39;00m add(\u001b[38;5;241m-\u001b[39m\u001b[38;5;241m1\u001b[39m, \u001b[38;5;241m1\u001b[39m) \u001b[38;5;241m==\u001b[39m \u001b[38;5;241m0\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mAdding -1 and 1 should give 0\u001b[39m\u001b[38;5;124m\"\u001b[39m\n","\u001b[0;31mAssertionError\u001b[0m: Adding 2 and 3 should give 5"]}],"source":["def add(x, y):\n","    return x + y\n","\n","# Test cases\n","assert add(2, 3) == 5, \"Adding 2 and 3 should give 5\"\n","assert add(-1, 1) == 0, \"Adding -1 and 1 should give 0\""]}],"metadata":{"colab":{"provenance":[],"toc_visible":true},"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.16"}},"nbformat":4,"nbformat_minor":0}
